version: "3"
services:
  emqx:
    image: emqx/emqx:5.6.1
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
      - 14567:14567/udp
    environment:
      - EMQX_LISTENERS__QUIC__DEFAULT__keyfile=etc/certs/key.pem
      - EMQX_LISTENERS__QUIC__DEFAULT__certfile=etc/certs/cert.pem
      - EMQX_LISTENERS__QUIC__DEFAULT__ENABLED=true
  # mqtt-client:
  #   image: local/python-mqtt-client
  #   container_name: mqtt-client
  # extra_hosts:
  #   - "host.docker.internal:host-gateway"
